name: Demo workflow GitHub Actions

on:
  push: 

jobs:
  job-1:
    environment: 
      name: Cow bells
      url: www.google.com
    runs-on: ubuntu-latest
    steps:
       - run: echo "hello world"
